import type { Metadata } from "next";
import Header from "@/components/layout/Header";
import { ThemeProvider } from "@/context/ThemeContext";
import PreviewHeader from "@/components/layout/PreviewHeader";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className=" dark:bg-background">
      <div className="p-5">
        <Header title="Devlink" />
        {/* <PreviewHeader /> */}
        {children}
      </div>
    </div>
  );
}
